# tips hat to Pádraic Brady, Dave Marshall, Wouter, Graham Campbell for this
filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*]
before_commands:
    - 'composer install --prefer-source'
    - 'wget https://s3-us-west-2.amazonaws.com/csvelte/csvsampledata.tar.gz'
    - 'tar xvfz csvsampledata.tar.gz -C tests/'
tools:
    external_code_coverage:
        timeout: 300
    php_code_sniffer: true
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_pdepend:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_hhvm: false
    php_mess_detector: true
    php_analyzer: true
changetracking:
    bug_patterns: ["\bfix(?:es|ed)?\b"]
    feature_patterns: ["\badd(?:s|ed)?\b", "\bimplement(?:s|ed)?\b", "\bresolve(?:s|d)?\b"]
